### ISSUE TITLE
ida7.0 export error

### ISSUE THREAD

**Issue by cattrace** [x64dbg/x64dbgida#11]
`5891 label(s) exported
Traceback (most recent call last):
  File "D:/IDA7/plugins/x64dbgida.py", line 358, in exportdb
    do_export()
  File "D:/IDA7/plugins/x64dbgida.py", line 201, in do_export
    } for (ea, comment) in Comments()]
  File "D:/IDA7/plugins/x64dbgida.py", line 45, in Comments
    for ea in range(MinEA(), MaxEA()):
  File "D:/IDA7/plugins/x64dbgida.py", line 18, in MinEA
    def MinEA(): return get_inf_attr(ida_ida.INF_MIN_EA)
AttributeError: 'module' object has no attribute 'INF_MIN_EA'
Error exporting database...
`

**Comment by cattrace** [comment]
python2.7

**Comment by mrexodia** [comment]
https://github.com/x64dbg/x64dbgida/releases

https://github.com/x64dbg/x64dbgida/archive/ida70.zip

**Comment by cattrace** [comment]
> https://github.com/x64dbg/x64dbgida/releases
> 
> https://github.com/x64dbg/x64dbgida/archive/ida70.zip

thanks! problem solved!
