### ISSUE TITLE
Import error UnicodeDecodeError

### ISSUE THREAD

**Issue by vananasun** [x64dbg/x64dbgida#14]
```
-----------------------------------------------------------------------------------------
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] 
IDAPython v7.4.0 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
-----------------------------------------------------------------------------------------
Importing database E:\dev\.____Stuff\latest-bout-dat.dd32
Traceback (most recent call last):
  File "C:/Apps/System/IDA_Pro_7.7/plugins/x64dbgida.py", line 322, in importdb
    do_import()
  File "C:/Apps/System/IDA_Pro_7.7/plugins/x64dbgida.py", line 102, in do_import
    db = json.load(dbdata)
  File "json\__init__.py", line 293, in load
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 205958: character maps to <undefined>
Error importing database...
```

if I know more I will post updates

**Comment by mrexodia** [comment]
Yeah the encoding should be utf-8.

**Comment by vananasun** [comment]
> Yeah the encoding should be utf-8.

It was an utf-8 database (uncompressed x32dbg export), so I actually had to change it in the script's open() statements with encoding='utf-8'.

**Comment by mrexodia** [comment]
Yes, this is a bug in the script.
